changelog:
  - version: v0.5.0
    categories:
      - title: Breaking
        labels: [breaking]
      - title: Features
        labels: [enhancement, feature]
      - title: Ops
        labels: [ops]
      - title: Docs
        labels: [documentation]
      - title: Fixes
        labels: [bug]
    exclude-labels: [skip-changelog]
    compare-url: true
    notes: .github/release-notes/v0.5.0.md