version: 2
project_name: scantrace-agent

before:
  hooks:
    - bash -lc 'set -euo pipefail; go mod download; cd scantrace-agent; go mod tidy; go mod download'

builds:
  - id: agent
    dir: ./scantrace-agent
    main: ./cmd/bot
    binary: scantrace-agent
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    flags:
      - -v

archives:
  - id: tarballs
    format: tar.gz
    wrap_in_directory: true
    name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
    files:
      - src: ./README.md
        dst: README.md
      - src: ./LICENSE
        dst: LICENSE
    ids:
      - agent

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs: '
      - '^chore: '

release:
  prerelease: auto
  draft: false
