// Package casebuilder renders Case records into Markdown reports and Slack Block Kit JSON.
package casebuilder

import (
	"encoding/json"
	"fmt"
	"regexp"
	"strings"
	"time"

	"github.com/Risen24x7/scantrace/internal/db"
)

type CaseReport struct {
	Case     *db.Case              `json:"case"`
	Events   []*db.Event           `json:"events"`
	Entities map[string]*db.Entity `json:"entities"`
	Markdown string                `json:"-"`
}

type Builder struct {
	store *db.DB
}

func New(store *db.DB) *Builder {
	return &Builder{store: store}
}

func (b *Builder) BuildReport(caseID string) (*CaseReport, error) {
	cas, err := b.store.GetCase(caseID)
	if err != nil || cas == nil {
		return nil, fmt.Errorf("casebuilder: case not found: %s", caseID)
	}
	var events []*db.Event
	for _, eid := range cas.RelatedEventIDs {
		evt, err := b.store.GetEvent(eid)
		if err != nil || evt == nil {
			continue
		}
		events = append(events, evt)
	}
	entities := make(map[string]*db.Entity)
	linkedEntities, err := b.store.GetEntitiesForCase(caseID)
	if err == nil {
		for _, ent := range linkedEntities {
			entities[ent.IP] = ent
		}
	}

	report := &CaseReport{Case: cas, Events: events, Entities: entities}
	report.Markdown = renderMarkdown(report)
	return report, nil
}

func BuildReportFromCase(cas *db.Case, events []*db.Event, entities map[string]*db.Entity) *CaseReport {
	r := &CaseReport{Case: cas, Events: events, Entities: entities}
	r.Markdown = renderMarkdown(r)
	return r
}

func (r *CaseReport) ToJSON() ([]byte, error) {
	return json.MarshalIndent(r, "", "  ")
}

func renderMarkdown(r *CaseReport) string {
	c := r.Case
	var b strings.Builder
	b.WriteString("# \U0001f6a8 ScanTrace Case Report\n\n")
	b.WriteString(fmt.Sprintf("**Case ID:** `%s`\n\n", c.CaseID))
	b.WriteString(fmt.Sprintf("**Title:** %s\n\n", c.Title))
	b.WriteString(fmt.Sprintf("**Status:** %s | **Severity:** %s | **Confidence:** %.0f%%\n\n",
		strings.ToUpper(c.Status), strings.ToUpper(c.Severity), c.Confidence*100))
	b.WriteString(fmt.Sprintf("**Generated:** %s\n\n", time.Now().UTC().Format(time.RFC3339)))
	b.WriteString("---\n\n## Summary\n\n")
	b.WriteString(c.Summary + "\n\n")
	if len(r.Entities) > 0 {
		b.WriteString("## Infrastructure Context\n\n")
		b.WriteString("| IP | ASN | Org | Country | RDNS | Abuse |\n|---|---|---|---|---|---|\n")
		for ip, ent := range r.Entities {
			b.WriteString(fmt.Sprintf("| %s | %s | %s | %s | %s | %s |\n",
				ip, ent.ASN, ent.ASName, ent.GeoCountry, ent.RDNS, ent.AbuseContact))
		}
		b.WriteString("\n")
	}
	if len(r.Events) > 0 {
		b.WriteString("## Event Timeline\n\n")
		b.WriteString("| Time | Src IP | Src Port | Dst IP | Dst Port | Proto | Type | Conf |\n|---|---|---|---|---|---|---|---|\n")
		for _, e := range r.Events {
			b.WriteString(fmt.Sprintf("| %s | %s | %d | %s | %d | %s | %s | %.0f%% |\n",
				e.Timestamp.Format("15:04:05"), e.SrcIP, e.SrcPort,
				e.DstIP, e.DstPort, strings.ToUpper(e.Protocol), e.EventType, e.Confidence*100))
		}
		b.WriteString("\n")
	}
	if c.AnalystNotes != "" {
		b.WriteString("## Analyst Notes\n\n" + c.AnalystNotes + "\n\n")
	}
	b.WriteString("---\n\n*Generated by ScanTrace — Dead Reckoning Edition*\n")
	return b.String()
}

// wellKnownPortLabel returns a short annotation for notable ports.
// Returns empty string for unrecognised ports.
func wellKnownPortLabel(port int) string {
	switch port {
	case 21:
		return "FTP"
	case 22:
		return "SSH"
	case 23:
		return "Telnet"
	case 25:
		return "SMTP"
	case 53:
		return "DNS"
	case 80:
		return "HTTP"
	case 110:
		return "POP3"
	case 143:
		return "IMAP"
	case 161:
		return "SNMP"
	case 443:
		return "HTTPS"
	case 445:
		return "SMB"
	case 1433:
		return "MSSQL"
	case 1723:
		return "PPTP VPN"
	case 3306:
		return "MySQL"
	case 3389:
		return "RDP"
	case 3388:
		return "RDP-alt ⚠️"
	case 5060:
		return "SIP/VoIP"
	case 5061:
		return "SIP-TLS"
	case 5432:
		return "PostgreSQL"
	case 5900:
		return "VNC"
	case 5985:
		return "WinRM HTTP"
	case 5986:
		return "WinRM HTTPS"
	case 6379:
		return "Redis"
	case 8080:
		return "HTTP-alt"
	case 8443:
		return "HTTPS-alt"
	case 8728:
		return "MikroTik Winbox"
	case 8729:
		return "MikroTik Winbox-TLS"
	case 9200:
		return "Elasticsearch"
	case 27017:
		return "MongoDB"
	default:
		return ""
	}
}

// boilerplateRE strips the full mechanical syslog summary boilerplate in one
// pass, covering both the main sentence and the trailing "First seen from X."
// sentence that the syslog ingestor appends.
//
// Pattern covers:
//
//	"Syslog-ingested DROP event(s) from <subnet> targeting port <n>."
//	"First seen from <ip>."
var boilerplateRE = regexp.MustCompile(
	`(?i)(?:syslog-ingested\s+drop\s+events?\s+from\s+\S+\s+targeting\s+port\s+\d+\.?\s*|first\s+seen\s+from\s+\S+\.?\s*)`,
)

// alertSnippet returns a clean body for the Slack alert snippet.
// All mechanical boilerplate is stripped. If nothing meaningful remains,
// a prompt to use /scantrace report is returned instead.
func alertSnippet(summary string) string {
	clean := strings.TrimSpace(boilerplateRE.ReplaceAllString(summary, ""))
	if clean != "" && len(clean) > 10 {
		if len(clean) > 280 {
			clean = clean[:280] + "\u2026"
		}
		return clean
	}
	return "_No additional analyst notes. Use `/scantrace report <id>` for full details._"
}

// extractAlertMeta pulls the first event's port, protocol, and source IP/subnet
// from the event list for use in the alert header.
func extractAlertMeta(events []*db.Event) (port int, proto string, srcSubnet string, firstSeenIP string) {
	for _, e := range events {
		if e == nil {
			continue
		}
		if port == 0 && e.DstPort > 0 {
			port = e.DstPort
		}
		if proto == "" && e.Protocol != "" {
			proto = strings.ToUpper(e.Protocol)
		}
		if firstSeenIP == "" && e.SrcIP != "" {
			firstSeenIP = e.SrcIP
			// Coalesce to /24 subnet for display
			parts := strings.Split(e.SrcIP, ".")
			if len(parts) == 4 {
				srcSubnet = parts[0] + "." + parts[1] + "." + parts[2] + ".0/24"
			} else {
				srcSubnet = e.SrcIP
			}
		}
		if port > 0 && proto != "" && firstSeenIP != "" {
			break
		}
	}
	return
}

// severityEmojiFor returns the severity dot emoji for any casing of sev.
func severityEmojiFor(sev string) string {
	switch strings.ToLower(strings.TrimSpace(sev)) {
	case "high":
		return "\U0001f534"
	case "medium":
		return "\U0001f7e1"
	case "low":
		return "\U0001f7e2"
	default:
		return "\u26aa"
	}
}

func (r *CaseReport) SlackBlock() map[string]interface{} {
	c := r.Case

	emoji := severityEmojiFor(c.Severity)

	port, proto, srcSubnet, firstSeenIP := extractAlertMeta(r.Events)

	// Build a structured header: 🟢  DROP · port 3388/TCP · 45.142.193.0/24 — LOW
	// Falls back to the case title when event meta is unavailable.
	var headerParts []string
	if port > 0 {
		portStr := fmt.Sprintf("port %d", port)
		if proto != "" {
			portStr += "/" + proto
		}
		headerParts = append(headerParts, portStr)
	}
	if srcSubnet != "" {
		headerParts = append(headerParts, srcSubnet)
	}

	var headerBody string
	if len(headerParts) > 0 {
		headerBody = "DROP · " + strings.Join(headerParts, " · ")
	} else {
		headerBody = c.Title
	}
	header := fmt.Sprintf("%s  *%s* — %s", emoji, headerBody, strings.ToUpper(c.Severity))

	// Fields grid: Events / Confidence / Status / Case ID
	fields := []map[string]string{
		{"type": "mrkdwn", "text": fmt.Sprintf("*Events:*\n%d", len(r.Events))},
		{"type": "mrkdwn", "text": fmt.Sprintf("*Confidence:*\n%.0f%%", c.Confidence*100)},
		{"type": "mrkdwn", "text": fmt.Sprintf("*Status:*\n%s", strings.ToUpper(c.Status))},
		{"type": "mrkdwn", "text": fmt.Sprintf("*Case ID:*\n`%s`", c.CaseID[:8])},
	}

	blocks := []map[string]interface{}{
		{"type": "section", "text": map[string]string{"type": "mrkdwn", "text": header}},
		{"type": "section", "fields": fields},
	}

	// Context line: port annotation + first-seen IP + entity enrichment
	var contextParts []string
	if port > 0 {
		if label := wellKnownPortLabel(port); label != "" {
			contextParts = append(contextParts, fmt.Sprintf("*%d* → %s", port, label))
		}
	}
	if firstSeenIP != "" {
		contextParts = append(contextParts, fmt.Sprintf("First seen: `%s`", firstSeenIP))
	}
	for ip, ent := range r.Entities {
		if ent.ASName != "" {
			contextParts = append(contextParts, fmt.Sprintf("`%s` · %s · %s", ip, ent.ASName, ent.GeoCountry))
		} else {
			contextParts = append(contextParts, fmt.Sprintf("`%s`", ip))
		}
		break
	}
	if len(contextParts) > 0 {
		blocks = append(blocks, map[string]interface{}{
			"type":     "context",
			"elements": []map[string]string{{"type": "mrkdwn", "text": strings.Join(contextParts, "   ·   ")}},
		})
	}

	// Summary block — all mechanical boilerplate stripped
	snippet := alertSnippet(c.Summary)
	blocks = append(blocks,
		map[string]interface{}{"type": "section", "text": map[string]string{"type": "mrkdwn", "text": snippet}},
		map[string]interface{}{"type": "divider"},
	)

	return map[string]interface{}{"blocks": blocks}
}
