// Package casebuilder renders Case records into Markdown reports and Slack Block Kit JSON.
package casebuilder

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"github.com/Risen24x7/scantrace/internal/db"
)

type CaseReport struct {
	Case     *db.Case              `json:"case"`
	Events   []*db.Event           `json:"events"`
	Entities map[string]*db.Entity `json:"entities"`
	Markdown string                `json:"-"`
}

type Builder struct {
	store *db.DB
}

func New(store *db.DB) *Builder {
	return &Builder{store: store}
}

func (b *Builder) BuildReport(caseID string) (*CaseReport, error) {
	cas, err := b.store.GetCase(caseID)
	if err != nil || cas == nil {
		return nil, fmt.Errorf("casebuilder: case not found: %s", caseID)
	}
	var events []*db.Event
	for _, eid := range cas.RelatedEventIDs {
		evt, err := b.store.GetEvent(eid)
		if err != nil || evt == nil {
			continue
		}
		events = append(events, evt)
	}
	entities := make(map[string]*db.Entity)
	for _, entID := range cas.RelatedEntityIDs {
		ent, err := b.store.GetEntity(entID)
		if err != nil || ent == nil {
			continue
		}
		entities[ent.IP] = ent
	}
	report := &CaseReport{Case: cas, Events: events, Entities: entities}
	report.Markdown = renderMarkdown(report)
	return report, nil
}

func BuildReportFromCase(cas *db.Case, events []*db.Event, entities map[string]*db.Entity) *CaseReport {
	r := &CaseReport{Case: cas, Events: events, Entities: entities}
	r.Markdown = renderMarkdown(r)
	return r
}

func (r *CaseReport) ToJSON() ([]byte, error) {
	return json.MarshalIndent(r, "", "  ")
}

func renderMarkdown(r *CaseReport) string {
	c := r.Case
	var b strings.Builder
	b.WriteString("# \U0001f6a8 ScanTrace Case Report\n\n")
	b.WriteString(fmt.Sprintf("**Case ID:** `%s`\n\n", c.CaseID))
	b.WriteString(fmt.Sprintf("**Title:** %s\n\n", c.Title))
	b.WriteString(fmt.Sprintf("**Status:** %s | **Severity:** %s | **Confidence:** %.0f%%\n\n",
		strings.ToUpper(c.Status), strings.ToUpper(c.Severity), c.Confidence*100))
	b.WriteString(fmt.Sprintf("**Generated:** %s\n\n", time.Now().UTC().Format(time.RFC3339)))
	b.WriteString("---\n\n## Summary\n\n")
	b.WriteString(c.Summary + "\n\n")
	if len(r.Entities) > 0 {
		b.WriteString("## Infrastructure Context\n\n")
		b.WriteString("| IP | ASN | Org | Country | RDNS | Abuse |\n|---|---|---|---|---|---|\n")
		for ip, ent := range r.Entities {
			b.WriteString(fmt.Sprintf("| %s | %s | %s | %s | %s | %s |\n",
				ip, ent.ASN, ent.ASName, ent.GeoCountry, ent.RDNS, ent.AbuseContact))
		}
		b.WriteString("\n")
	}
	if len(r.Events) > 0 {
		b.WriteString("## Event Timeline\n\n")
		b.WriteString("| Time | Src IP | Src Port | Dst IP | Dst Port | Proto | Type | Conf |\n|---|---|---|---|---|---|---|---|\n")
		for _, e := range r.Events {
			b.WriteString(fmt.Sprintf("| %s | %s | %d | %s | %d | %s | %s | %.0f%% |\n",
				e.Timestamp.Format("15:04:05"), e.SrcIP, e.SrcPort,
				e.DstIP, e.DstPort, strings.ToUpper(e.Protocol), e.EventType, e.Confidence*100))
		}
		b.WriteString("\n")
	}
	if c.AnalystNotes != "" {
		b.WriteString("## Analyst Notes\n\n" + c.AnalystNotes + "\n\n")
	}
	b.WriteString("---\n\n*Generated by ScanTrace — Dead Reckoning Edition*\n")
	return b.String()
}

func (r *CaseReport) SlackBlock() map[string]interface{} {
	c := r.Case
	emoji := map[string]string{"high": "\U0001f534", "medium": "\U0001f7e1", "low": "\U0001f7e2"}[c.Severity]
	if emoji == "" {
		emoji = "\u26aa"
	}
	header := fmt.Sprintf("%s *%s* — %s", emoji, c.Title, strings.ToUpper(c.Severity))
	entityLine := ""
	for ip, ent := range r.Entities {
		if ent.ASName != "" {
			entityLine = fmt.Sprintf("`%s` \u00b7 %s \u00b7 %s", ip, ent.ASName, ent.GeoCountry)
		} else {
			entityLine = fmt.Sprintf("`%s`", ip)
		}
		break
	}
	snippet := c.Summary
	if len(snippet) > 300 {
		snippet = snippet[:300] + "\u2026"
	}
	blocks := []map[string]interface{}{
		{"type": "section", "text": map[string]string{"type": "mrkdwn", "text": header}},
		{"type": "section", "fields": []map[string]string{
			{"type": "mrkdwn", "text": fmt.Sprintf("*Events:*\n%d", len(r.Events))},
			{"type": "mrkdwn", "text": fmt.Sprintf("*Confidence:*\n%.0f%%", c.Confidence*100)},
			{"type": "mrkdwn", "text": fmt.Sprintf("*Status:*\n%s", strings.ToUpper(c.Status))},
			{"type": "mrkdwn", "text": fmt.Sprintf("*Case ID:*\n`%s`", c.CaseID[:8]+"\u2026")},
		}},
	}
	if entityLine != "" {
		blocks = append(blocks, map[string]interface{}{
			"type":     "context",
			"elements": []map[string]string{{"type": "mrkdwn", "text": entityLine}},
		})
	}
	blocks = append(blocks,
		map[string]interface{}{"type": "section", "text": map[string]string{"type": "mrkdwn", "text": snippet}},
		map[string]interface{}{"type": "divider"},
	)
	return map[string]interface{}{"blocks": blocks}
}
